### ISSUE TITLE
configurable BypassProcessList

### ISSUE THREAD

**Issue by mokurin000** [imbushuo/EnergyStar#16]
Currently BypassProcessList is hard coded.
I think it's better be configurable.
e.g. custom IME's process name, or IDE without auto-save

Compares to build the program again, modify a configuration is much more user-friendly and graceful

**Comment by kxxt** [comment]
It's implemented in #11. imbushuo wants to make some changes(make it more user friendly) before merging it into master branch.

If you can't wait to have this feature, you can download the exe from [CI builds](https://github.com/imbushuo/EnergyStar/actions/runs/2767974788) and put [this settings.json file](https://github.com/kxxt/EnergyStar/blob/b98c1b336d73250cda5b8cf789707e281dd469a3/EnergyStar/settings.json) alongside the executable.

**Comment by poly000** [comment]
close as solved
