### ISSUE TITLE
Soon, applications developer will start build website to protest

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [imbushuo/EnergyStar#17]
https://dontkillmyapp.com

![image](https://user-images.githubusercontent.com/10773245/182816547-34a6e520-1622-4179-9e9d-bc4e37ff84d9.png)

**Comment by kxxt** [comment]
I don't think so. EnergyStar won't kill any app. What it does is just changing EcoQoS mode of processes.

**Comment by mhtvsSFrpHdE** [comment]
Failed joke. Never mind.
